version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: safekids-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: safekids_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password


volumes:
  db_data:
